apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fplbot.fullname" . }}
  labels:
    {{- include "fplbot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fplbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "fplbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fplbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.aspnetcore.environment }}
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.service.targetPort }}"
            {{- if .Values.config.footballData.baseUrl }}
            - name: FOOTBALL_DATA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "fplbot.fullname" . }}-secrets
                  key: football-data-base-url
            {{- end }}
            {{- if .Values.config.footballData.apiToken }}
            - name: FOOTBALL_DATA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "fplbot.fullname" . }}-secrets
                  key: football-data-api-token
            {{- end }}
            {{- if .Values.config.oddsApi.baseUrl }}
            - name: ODDS_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "fplbot.fullname" . }}-secrets
                  key: odds-api-base-url
            {{- end }}
            {{- if .Values.config.oddsApi.apiToken }}
            - name: ODDS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "fplbot.fullname" . }}-secrets
                  key: odds-api-token
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.config.enabled }}
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
              readOnly: true
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.config.enabled }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fplbot.fullname" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}