name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    permissions:
      contents: read
      packages: write

    uses: justinmarkmarshall/github-actions/.github/workflows/dotnet-test-build-push.yml@main
    with:
      solution: FplBot.sln
      dotnet-version: "10.0.x"