name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    permissions:
      contents: read
      packages: write

    uses: justinmarkmarshall/github-actions/.github/workflows/build-push-ghcr.yml@main