name: Debug Permissions

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          
      - name: Test GHCR Login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "Login successful!"
          
      - name: Test Docker Build
        run: |
          docker build -t test-image .
          echo "Build successful!"
          
      - name: Test Tag and Push
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}:test"
          docker tag test-image $IMAGE_NAME
          echo "Tagged as: $IMAGE_NAME"
          docker push $IMAGE_NAME
          echo "Push successful!"